# Generated by Django 2.1.5 on 2019-02-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('1', 'Муж'), ('2', 'Жен')], max_length=10)),
                ('date_birthday', models.DateField()),
            ],
        ),
    ]
